const defaultData = {
  couple: {
    names: "Vanessa & Jeremy",
    location: "Aoki Lake, Nagano",
    date: "May 2–6, 2027",
    guests: "~40 guests",
    updated: "March 3, 2026",
  },
  desiredBudget: "AU$22,500",
  planningFee: 9200,
  milestones: [
    { id: "m1", label: "Planning Begins", target: "Mar 2026", status: "done" },
    { id: "m2", label: "Venue Confirmed", target: "May 2026", status: "current" },
    { id: "m3", label: "Vendors Booked", target: "Aug 2026", status: "upcoming" },
    { id: "m4", label: "Save the Dates", target: "Sep 2026", status: "upcoming" },
    { id: "m5", label: "RSVPs Due", target: "Jan 2027", status: "upcoming" },
    { id: "m6", label: "Final Details", target: "Apr 2027", status: "upcoming" },
    { id: "m7", label: "Wedding Week", target: "May 2027", status: "upcoming" },
  ],
  decisions: [
    {
      id: "d1", title: "Minpaku Property", status: "active",
      description: "Confirm the Omachi chalet or choose from alternative minpaku options Juri is researching. Key factors: garden size, guest capacity (40), kitchen facilities for catering, number of beds.",
      deadline: "April 30, 2026", priority: "high", notes: [],
    },
    {
      id: "d2", title: "Ceremony Location", status: "active",
      description: "Outdoor ceremony at a scenic spot near Aoki Lake with transport back to the minpaku, or hold everything on-site in the garden. We're scouting 2-3 nearby options.",
      deadline: "April 30, 2026", priority: "high", notes: [],
    },
    {
      id: "d3", title: "Reception Format", status: "active",
      description: "Seated dinner vs. standing cocktail style in the minpaku garden. Affects catering quotes, furniture rental, layout, and weather backup planning.",
      deadline: "May 30, 2026", priority: "high", notes: [],
    },
    {
      id: "d4", title: "Catering", status: "on-horizon",
      description: "Style of food and drink service. Options range from local caterer to private chef. Depends on reception format and venue kitchen facilities.",
      deadline: "June 2026", priority: "medium", notes: [],
    },
    {
      id: "d5", title: "Activity Day Itinerary (May 3)", status: "on-horizon",
      description: "Group outing options: guided hike, onsen visit, sake brewery tour, lake activities, or a mix. We'll propose itineraries once venue is locked.",
      deadline: "August 2026", priority: "medium", notes: [],
    },
    {
      id: "d6", title: "Ceremony Styling & Florals", status: "on-horizon",
      description: "Arch/altar design, floral arrangements, aisle styling. Based on your moodboard aesthetic. Depends on ceremony location choice.",
      deadline: "September 2026", priority: "medium", notes: [],
    },
    {
      id: "d7", title: "Furniture & Rentals", status: "on-horizon",
      description: "Tables, chairs, lighting, tableware for the garden reception. Style depends on reception format and your aesthetic vision.",
      deadline: "September 2026", priority: "low", notes: [],
    },
    {
      id: "d8", title: "Guest Accommodation Overflow", status: "on-horizon",
      description: "The minpaku may not sleep all 40 guests. We'll need to identify nearby lodging options and decide how to communicate those to guests.",
      deadline: "October 2026", priority: "medium", notes: [],
    },
    {
      id: "d9", title: "Guest Transport & Logistics", status: "on-horizon",
      description: "How guests get from Tokyo/airport to Nagano, and between the ceremony site and minpaku if they're separate. Charter bus, train info pack, or both.",
      deadline: "November 2026", priority: "low", notes: [],
    },
    {
      id: "d10", title: "Hair & Makeup", status: "on-horizon",
      description: "Book artist(s) for Vanessa and bridal party. Limited availability in rural Nagano so may need someone from Matsumoto or Nagano City.",
      deadline: "October 2026", priority: "low", notes: [],
    },
    {
      id: "d11", title: "Weather Backup Plan", status: "on-horizon",
      description: "Contingency for rain during outdoor ceremony and/or garden reception. Indoor alternatives at the minpaku, tent rental, or timing adjustments.",
      deadline: "January 2027", priority: "medium", notes: [],
    },
  ],
  inProgress: [
    { id: "p1", task: "Researching alternative minpaku properties in the Omachi / Aoki Lake area", owner: "Juri", started: "Feb 25, 2026", notes: [] },
    { id: "p2", task: "Getting catering quotes for 40-person outdoor reception", owner: "Juri", started: "Mar 1, 2026", notes: [] },
    { id: "p3", task: "Scouting nearby ceremony locations with lake or mountain views", owner: "Juri", started: "Mar 1, 2026", notes: [] },
    { id: "p4", task: "Developing weather contingency options for outdoor events", owner: "Eamon & Juri", started: "Mar 3, 2026", notes: [] },
  ],
  completed: [
    { id: "c1", task: "Discovery call", date: "Feb 19, 2026", notes: [] },
    { id: "c2", task: "Proposal delivered and reviewed", date: "Feb 26, 2026", notes: [] },
    { id: "c3", task: "Planning agreement signed", date: "Mar 1, 2026", notes: [] },
    { id: "c4", task: "Initial deposit received", date: "Mar 1, 2026", notes: [] },
    { id: "c5", task: "Reviewed Vanessa's Pinterest moodboard", date: "Mar 2, 2026", notes: [] },
  ],
  days: [
    {
      id: "day1", dayNum: 1, dateLabel: "Friday, May 2", title: "Arrival Day",
      summary: "Guests arrive at the minpaku property. First impressions of the lake and mountains. Casual welcome gathering in the evening to set the tone for the weekend.",
      tasks: [
        { id: "dt1", text: "Welcome drinks and snacks organised", status: "todo" },
        { id: "dt2", text: "Guest room assignments confirmed", status: "todo" },
        { id: "dt3", text: "Transport from station arranged", status: "todo" },
      ],
      decisionsNeeded: ["Guest transport logistics", "Welcome evening format (casual drinks vs. organised dinner)"],
    },
    {
      id: "day2", dayNum: 2, dateLabel: "Saturday, May 3", title: "Activity Day",
      summary: "A full group day out exploring the area. This is about giving your guests an unforgettable Japan experience beyond the wedding itself. The vibe is relaxed, fun, and shared adventure.",
      tasks: [
        { id: "dt4", text: "Activity itinerary finalised", status: "todo" },
        { id: "dt5", text: "Transport/guides booked", status: "todo" },
        { id: "dt6", text: "Lunch arrangements confirmed", status: "todo" },
      ],
      decisionsNeeded: ["Activity day itinerary (hike, onsen, brewery, or mix)"],
    },
    {
      id: "day3", dayNum: 3, dateLabel: "Sunday, May 4", title: "Wedding Day",
      summary: "The main event. Ceremony at your chosen location, followed by reception and dinner in the minpaku garden. Every detail of this day gets its own dedicated planning track.",
      tasks: [
        { id: "dt7", text: "Ceremony location and setup confirmed", status: "todo" },
        { id: "dt8", text: "Reception layout and furniture arranged", status: "todo" },
        { id: "dt9", text: "Catering confirmed and menu finalised", status: "todo" },
        { id: "dt10", text: "Florals and styling confirmed", status: "todo" },
        { id: "dt11", text: "Hair & makeup booked", status: "todo" },
        { id: "dt12", text: "Day-of timeline created", status: "todo" },
        { id: "dt13", text: "Weather backup plan ready", status: "todo" },
      ],
      decisionsNeeded: ["Ceremony location", "Reception format", "Catering style", "Florals & styling", "Weather backup"],
    },
    {
      id: "day4", dayNum: 4, dateLabel: "Monday, May 5", title: "Recovery Day",
      summary: "A relaxed, informal day together. No agenda required. Maybe a farewell brunch, a quiet walk by the lake, or just time to soak in the setting before people start to leave.",
      tasks: [
        { id: "dt14", text: "Farewell brunch arrangements (if wanted)", status: "todo" },
        { id: "dt15", text: "Cleanup and vendor pack-down coordinated", status: "todo" },
      ],
      decisionsNeeded: ["Whether to organise a farewell brunch or keep it fully unstructured"],
    },
    {
      id: "day5", dayNum: 5, dateLabel: "Tuesday, May 6", title: "Departure",
      summary: "Guests check out and head home or continue their Japan trip. We'll prepare a suggested onward travel guide for guests who want to explore more.",
      tasks: [
        { id: "dt16", text: "Checkout logistics confirmed with property", status: "todo" },
        { id: "dt17", text: "Guest onward travel suggestions prepared", status: "todo" },
      ],
      decisionsNeeded: [],
    },
  ],
  budget: [
    { id: "b1", label: "Accommodation: family property (~20 pax, 4 nights)", low: 3300, high: 6000, status: "Researching" },
    { id: "b2", label: "Accommodation: friends property (16–20 pax, 4 nights)", low: 3300, high: 6000, status: "Researching" },
    { id: "b3", label: "Ceremony and reception venue hire", low: 800, high: 5000, status: "Researching" },
    { id: "b4", label: "Welcome gathering: food, drink, setup (40 pax)", low: 1250, high: 3500, status: "Not started" },
    { id: "b5", label: "Reception dinner: food, drink, service (40 pax)", low: 1450, high: 7200, status: "Quoting" },
    { id: "b6", label: "Florals and styling", low: 1800, high: 3600, status: "Not started" },
    { id: "b7", label: "Equipment hire: tables, chairs, lighting, PA, rain backup", low: 1450, high: 4500, status: "Not started" },
    { id: "b8", label: "Transport: station transfers and wedding day shuttles", low: 1250, high: 2800, status: "Not started" },
    { id: "b9", label: "Group activity (Day 2)", low: 450, high: 1500, status: "Not started" },
    { id: "b10", label: "Farewell brunch (40 pax)", low: 540, high: 1260, status: "Not started" },
    { id: "b11", label: "Ceremony officiant", low: 450, high: 900, status: "Not started" },
  ],
  budgetNote: "Photography & videography handled by your friends. All estimates in AUD. Ranges will narrow as we confirm venues and vendors.",
  checklist: [
    { id: "cl1", timeline: "12+ Months", category: "Administration", task: "Initial Consultation & Vision Setting", note: "Identify stakeholders", status: "done", notes: [] },
    { id: "cl2", timeline: "12+ Months", category: "Administration", task: "Budget Creation (include Japan buffer)", note: "Include contingency fund", status: "done", notes: [] },
    { id: "cl3", timeline: "12+ Months", category: "Administration", task: "Contract & Deposit", note: "Planning agreement", status: "done", notes: [] },
    { id: "cl4", timeline: "12+ Months", category: "Culture", task: "Cultural Integration Strategy", note: "Interview for non-negotiables", status: "not-started", notes: [] },
    { id: "cl5", timeline: "12+ Months", category: "Culture", task: "Family / Communication Plan", note: "Set boundaries and roles", status: "not-started", notes: [] },
    { id: "cl6", timeline: "12+ Months", category: "Venue", task: "Venue Scouting", note: "Ceremony & reception", status: "in-progress", notes: [] },
    { id: "cl7", timeline: "12+ Months", category: "Internal", task: "Accommodations & Planner Travel", note: "", status: "not-started", notes: [] },
    { id: "cl8", timeline: "9–12 Months", category: "Venue", task: "Venue Finalization", note: "Sign contracts", status: "not-started", notes: [] },
    { id: "cl9", timeline: "9–12 Months", category: "Venue", task: "Permit Verification", note: "Shrines / parks / public spots", status: "not-started", notes: [] },
    { id: "cl10", timeline: "9–12 Months", category: "Vendors", task: "Core Vendors (Officiant)", note: "Book ASAP", status: "not-started", notes: [] },
    { id: "cl11", timeline: "9–12 Months", category: "Guest Mgmt", task: "Save the Dates", note: "Distribute", status: "not-started", notes: [] },
    { id: "cl12", timeline: "9–12 Months", category: "Attire", task: "Attire Strategy (Rent vs. Bring)", note: "Create logistics plan", status: "not-started", notes: [] },
    { id: "cl13", timeline: "6–9 Months", category: "Styling", task: "Hair & Makeup (HMU)", note: "Book artist", status: "not-started", notes: [] },
    { id: "cl14", timeline: "6–9 Months", category: "Decor", task: "Decor & Florals Concept", note: "Color palette / rentals", status: "not-started", notes: [] },
    { id: "cl15", timeline: "6–9 Months", category: "Attire", task: "Measurements (Suit / Dress / Kimono)", note: "Send to boutiques if renting", status: "not-started", notes: [] },
    { id: "cl16", timeline: "6–9 Months", category: "Attire", task: "Attire Selection Finalized", note: "Ordering / booking", status: "not-started", notes: [] },
    { id: "cl17", timeline: "6–9 Months", category: "Guest Mgmt", task: "Dietary / Mobility / Medical Survey", note: "Send to guests", status: "not-started", notes: [] },
    { id: "cl18", timeline: "6–9 Months", category: "Logistics", task: "Insurance Requirement Clause", note: "Send to couple for website", status: "not-started", notes: [] },
    { id: "cl19", timeline: "6–9 Months", category: "Logistics", task: "Emergency Contact List Creation", note: "Hospitals / embassies", status: "not-started", notes: [] },
    { id: "cl20", timeline: "3–6 Months", category: "Music", task: "Band / DJ / Music Selection", note: "Ceremony & reception", status: "not-started", notes: [] },
    { id: "cl21", timeline: "3–6 Months", category: "Guest Mgmt", task: "Formal Invitations", note: "Send with RSVP deadline", status: "not-started", notes: [] },
    { id: "cl22", timeline: "3–6 Months", category: "Experience", task: "Activity / Restaurant Scouting", note: "Reservations", status: "not-started", notes: [] },
    { id: "cl23", timeline: "3–6 Months", category: "Venue", task: "Rain Plan Finalization", note: "Mandatory for outdoors", status: "not-started", notes: [] },
    { id: "cl24", timeline: "3–6 Months", category: "Venue", task: "Reception Menu Finalization", note: "Food / drink / cake", status: "not-started", notes: [] },
    { id: "cl25", timeline: "3–6 Months", category: "Logistics", task: "Transportation Logistics", note: "Shuttles / transit", status: "not-started", notes: [] },
    { id: "cl26", timeline: "1–3 Months", category: "Experience", task: "Final Itinerary", note: "Couple & guest versions", status: "not-started", notes: [] },
    { id: "cl27", timeline: "1–3 Months", category: "Venue", task: "After Party Scouting / Booking", note: "If applicable", status: "not-started", notes: [] },
    { id: "cl28", timeline: "1–3 Months", category: "Attire", task: "Pre-Wedding Steaming / Pressing", note: "Book local service", status: "not-started", notes: [] },
    { id: "cl29", timeline: "1–3 Months", category: "Attire", task: "Style Survival Kit", note: "Pins, tape, etc.", status: "not-started", notes: [] },
    { id: "cl30", timeline: "1 Month", category: "Internal", task: "Final Walkthrough", note: "Flow / logistics check", status: "not-started", notes: [] },
    { id: "cl31", timeline: "1 Month", category: "Guest Mgmt", task: "Final Headcount (wedding and activities)", note: "Update vendors", status: "not-started", notes: [] },
    { id: "cl32", timeline: "Week Of", category: "Internal", task: "Day-Of Kit", note: "Planner emergency gear", status: "not-started", notes: [] },
    { id: "cl33", timeline: "Week Of", category: "Internal", task: "Vendor Confirmation", note: "Final arrival times", status: "not-started", notes: [] },
  ],
};

export default defaultData;
