const defaultData = {
  couple: {
    names: "Vanessa & Jeremy",
    location: "Aoki Lake, Nagano",
    date: "May 2–6, 2027",
    guests: "~40 guests",
    updated: "March 3, 2026",
  },
  desiredBudget: "AU$22,500",
  planningFee: 9200,
  milestones: [
    { id: "m1", label: "Planning Begins", target: "Mar 2026", status: "done" },
    { id: "m2", label: "Venue Confirmed", target: "May 2026", status: "current" },
    { id: "m3", label: "Vendors Booked", target: "Aug 2026", status: "upcoming" },
    { id: "m4", label: "Save the Dates", target: "Sep 2026", status: "upcoming" },
    { id: "m5", label: "RSVPs Due", target: "Jan 2027", status: "upcoming" },
    { id: "m6", label: "Final Details", target: "Apr 2027", status: "upcoming" },
    { id: "m7", label: "Wedding Week", target: "May 2027", status: "upcoming" },
  ],
  decisions: [],
  inProgress: [],
  completed: [],
  days: [
    {
      id: "day1", dayNum: 1, dateLabel: "Friday, May 2", title: "Arrival Day",
      summary: "Guests arrive at the minpaku property. First impressions of the lake and mountains. Casual welcome gathering in the evening to set the tone for the weekend.",
      tasks: [
        { id: "dt1", text: "Welcome drinks and snacks organised", status: "todo" },
        { id: "dt2", text: "Guest room assignments confirmed", status: "todo" },
        { id: "dt3", text: "Transport from station arranged", status: "todo" },
      ],
      decisionsNeeded: ["Guest transport logistics", "Welcome evening format (casual drinks vs. organised dinner)"],
    },
    {
      id: "day2", dayNum: 2, dateLabel: "Saturday, May 3", title: "Activity Day",
      summary: "A full group day out exploring the area. This is about giving your guests an unforgettable Japan experience beyond the wedding itself. The vibe is relaxed, fun, and shared adventure.",
      tasks: [
        { id: "dt4", text: "Activity itinerary finalised", status: "todo" },
        { id: "dt5", text: "Transport/guides booked", status: "todo" },
        { id: "dt6", text: "Lunch arrangements confirmed", status: "todo" },
      ],
      decisionsNeeded: ["Activity day itinerary (hike, onsen, brewery, or mix)"],
    },
    {
      id: "day3", dayNum: 3, dateLabel: "Sunday, May 4", title: "Wedding Day",
      summary: "The main event. Ceremony at your chosen location, followed by reception and dinner in the minpaku garden. Every detail of this day gets its own dedicated planning track.",
      tasks: [
        { id: "dt7", text: "Ceremony location and setup confirmed", status: "todo" },
        { id: "dt8", text: "Reception layout and furniture arranged", status: "todo" },
        { id: "dt9", text: "Catering confirmed and menu finalised", status: "todo" },
        { id: "dt10", text: "Florals and styling confirmed", status: "todo" },
        { id: "dt11", text: "Hair & makeup booked", status: "todo" },
        { id: "dt12", text: "Day-of timeline created", status: "todo" },
        { id: "dt13", text: "Weather backup plan ready", status: "todo" },
      ],
      decisionsNeeded: ["Ceremony location", "Reception format", "Catering style", "Florals & styling", "Weather backup"],
    },
    {
      id: "day4", dayNum: 4, dateLabel: "Monday, May 5", title: "Recovery Day",
      summary: "A relaxed, informal day together. No agenda required. Maybe a farewell brunch, a quiet walk by the lake, or just time to soak in the setting before people start to leave.",
      tasks: [
        { id: "dt14", text: "Farewell brunch arrangements (if wanted)", status: "todo" },
        { id: "dt15", text: "Cleanup and vendor pack-down coordinated", status: "todo" },
      ],
      decisionsNeeded: ["Whether to organise a farewell brunch or keep it fully unstructured"],
    },
    {
      id: "day5", dayNum: 5, dateLabel: "Tuesday, May 6", title: "Departure",
      summary: "Guests check out and head home or continue their Japan trip. We'll prepare a suggested onward travel guide for guests who want to explore more.",
      tasks: [
        { id: "dt16", text: "Checkout logistics confirmed with property", status: "todo" },
        { id: "dt17", text: "Guest onward travel suggestions prepared", status: "todo" },
      ],
      decisionsNeeded: [],
    },
  ],
  budget: [
    { id: "b1", label: "Accommodation: family property (~20 pax, 4 nights)", low: 3300, high: 6000, status: "Researching" },
    { id: "b2", label: "Accommodation: friends property (16–20 pax, 4 nights)", low: 3300, high: 6000, status: "Researching" },
    { id: "b3", label: "Ceremony and reception venue hire", low: 800, high: 5000, status: "Researching" },
    { id: "b4", label: "Welcome gathering: food, drink, setup (40 pax)", low: 1250, high: 3500, status: "Not started" },
    { id: "b5", label: "Reception dinner: food, drink, service (40 pax)", low: 1450, high: 7200, status: "Quoting" },
    { id: "b6", label: "Florals and styling", low: 1800, high: 3600, status: "Not started" },
    { id: "b7", label: "Equipment hire: tables, chairs, lighting, PA, rain backup", low: 1450, high: 4500, status: "Not started" },
    { id: "b8", label: "Transport: station transfers and wedding day shuttles", low: 1250, high: 2800, status: "Not started" },
    { id: "b9", label: "Group activity (Day 2)", low: 450, high: 1500, status: "Not started" },
    { id: "b10", label: "Farewell brunch (40 pax)", low: 540, high: 1260, status: "Not started" },
    { id: "b11", label: "Ceremony officiant", low: 450, high: 900, status: "Not started" },
  ],
  budgetNote: "Photography & videography handled by your friends. All estimates in AUD. Ranges will narrow as we confirm venues and vendors.",
  checklist: [
    { id: "cl1", num: 1, phase: "12+", category: "Strategic Foundation", task: "Marriage approach decision", details: "Symbolic ceremony in Japan + legal registration in Australia, or full legal process through Australian Embassy in Tokyo. Shapes ceremony structure.", timeline: "12+ months", owner: "shared", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl2", num: 2, phase: "12+", category: "Strategic Foundation", task: "Locate mother-in-law hometown", details: "Pinpoint specific village/city to establish venue search radius.", timeline: "12+ months", owner: "shared", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl3", num: 3, phase: "12+", category: "Strategic Foundation", task: "Two-Hub Lodging Strategy", details: "Secure primary venue/resort as main guest hub + satellite Airbnb for overflow and bridal party prep.", timeline: "12+ months", owner: "us", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl4", num: 4, phase: "12+", category: "Strategic Foundation", task: "Golden Week conflict check", details: "May 1-5 is peak Nagano domestic travel. If dates overlap, finalize all bookings immediately.", timeline: "12+ months", owner: "us", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl5", num: 5, phase: "12+", category: "Strategic Foundation", task: "Officiant search and booking", details: "Licensed celebrant, friend, or symbolic-only? English-speaking celebrants in rural Japan are limited. Start early.", timeline: "12+ months", owner: "us", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl6", num: 6, phase: "12+", category: "Strategic Foundation", task: "Event liability insurance", details: "Research coverage for hosting 40 people at a private property. Some minpaku owners require this.", timeline: "12+ months", owner: "them", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl7", num: 7, phase: "12+", category: "Strategic Foundation", task: "Travel insurance recommendation", details: "Flag to couple and guests: secure policies covering Japan trip (medical, cancellation, luggage).", timeline: "12+ months", owner: "them", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl8", num: 8, phase: "12+", category: "Strategic Foundation", task: "Lock planning fee and payment schedule", details: "Confirm fee, payment installments, and collect first payment.", timeline: "12+ months", owner: "us", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl9", num: 9, phase: "12+", category: "Strategic Foundation", task: "Establish master budget", details: "Set all-in budget target with couple and agree on category allocations.", timeline: "12+ months", owner: "shared", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl10", num: 10, phase: "12+", category: "Strategic Foundation", task: "Confirm venue property", details: "Garden size, kitchen audit, bed count, guest capacity for 40. Omachi chalet vs. alternatives Juri is researching.", timeline: "12+ months", owner: "us", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl11", num: 11, phase: "12-6", category: "Venues and Accommodation", task: "Confirm ceremony location", details: "On-site garden ceremony vs. scenic off-site near Aoki Lake with transport back. Scout 2-3 options.", timeline: "12-6 months", owner: "us", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl12", num: 12, phase: "12-6", category: "Venues and Accommodation", task: "Plan B ceremony location", details: "Indoor backup or covered alternative in case of rain. Identify and reserve.", timeline: "12-6 months", owner: "us", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl13", num: 13, phase: "12-6", category: "Venues and Accommodation", task: "Satellite accommodation", details: "If minpaku does not sleep all 40, book nearby hotel block or second property for overflow.", timeline: "12-6 months", owner: "us", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl14", num: 14, phase: "12-6", category: "Catering and Food", task: "Catering decision", details: "Private chef (intimate, hyper-local) vs. full-service caterer (handles rentals/cleanup) vs. local restaurant.", timeline: "12-6 months", owner: "us", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl15", num: 15, phase: "12-6", category: "Catering and Food", task: "Kitchen audit (if private chef)", details: "Verify kitchen equipment, prep space, and utilities at the Airbnb/minpaku.", timeline: "12-6 months", owner: "us", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl16", num: 16, phase: "12-6", category: "Catering and Food", task: "Cake / dessert decision", details: "Separate wedding cake, dessert course from caterer, or local Nagano specialty (fruit-based options).", timeline: "12-6 months", owner: "shared", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl17", num: 17, phase: "12-6", category: "Catering and Food", task: "Dietary and allergy collection system", details: "Build into RSVP/wedding website. Ensure caterer can accommodate.", timeline: "12-6 months", owner: "us", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl18", num: 18, phase: "12-6", category: "Key Vendors", task: "HMUA search and selection", details: "Research and shortlist hair/makeup artists available in Nagano. Book early.", timeline: "12-6 months", owner: "us", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl19", num: 19, phase: "12-6", category: "Key Vendors", task: "Ceremony music booking", details: "String duo, harpist, or koto player. Scout availability for May 2027.", timeline: "12-6 months", owner: "us", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl20", num: 20, phase: "12-6", category: "Key Vendors", task: "Florist booking", details: "Full scope: arch/altar, bouquets, boutonnieres, table centerpieces, welcome arrangement, aisle clusters.", timeline: "12-6 months", owner: "us", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl21", num: 21, phase: "12-6", category: "Key Vendors", task: "Rentals company booking", details: "Tables, chairs, linens, glassware, flatware, lighting, sound system.", timeline: "12-6 months", owner: "us", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl22", num: 22, phase: "12-6", category: "Key Vendors", task: "Photographer coordination", details: "They are bringing their own. Coordinate: travel dates, location scout call, day-of timeline, first look timing, golden hour windows.", timeline: "12-6 months", owner: "shared", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl23", num: 23, phase: "12-6", category: "Guest Communications", task: "Finalize guest list", details: "Couple provides final list with names, emails, countries of origin.", timeline: "12-6 months", owner: "them", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl24", num: 24, phase: "12-6", category: "Guest Communications", task: "Save the dates sent", details: "Include travel lead time notice since it is international. Flag Golden Week flight pricing.", timeline: "12-6 months", owner: "them", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl25", num: 25, phase: "12-6", category: "Guest Communications", task: "Wedding website", details: "Build or WithJoy: travel instructions, accommodation info, itinerary overview, RSVP form, dietary questions, Japan travel FAQ.", timeline: "12-6 months", owner: "shared", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl26", num: 26, phase: "12-6", category: "Design and Aesthetic", task: "Confirm arch/altar style and floral palette", details: "Pale pink peonies, sweet peas, ranunculus + local Nagano cedar/hinoki. Deconstructed or floating arch.", timeline: "12-6 months", owner: "shared", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl27", num: 27, phase: "12-6", category: "Design and Aesthetic", task: "Ceremony seating decision", details: "Light wood cross-back chairs (rustic) or white bentwood (classic).", timeline: "12-6 months", owner: "shared", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl28", num: 28, phase: "12-6", category: "Design and Aesthetic", task: "Reception table styling direction", details: "Centerpiece style, place settings, any signage concepts. Tie to pale pink and nature aesthetic.", timeline: "12-6 months", owner: "shared", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl29", num: 29, phase: "6-3", category: "Guest Management", task: "Formal invitations sent", details: "Via wedding website or physical. Include RSVP deadline.", timeline: "6-3 months", owner: "them", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl30", num: 30, phase: "6-3", category: "Guest Management", task: "RSVP deadline and tracking", details: "Set deadline, build tracking system. Couple chases non-responders.", timeline: "6-3 months", owner: "shared", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl31", num: 31, phase: "6-3", category: "Guest Management", task: "Collect dietary restrictions and accessibility needs", details: "Pulled from RSVP data. Compile and share with caterer.", timeline: "6-3 months", owner: "us", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl32", num: 32, phase: "6-3", category: "Guest Management", task: "Guest welcome packets planned", details: "Design contents: itinerary cards, transport schedule, emergency contacts, local Nagano treats.", timeline: "6-3 months", owner: "us", status: "not-started", weddingDay: "day1", notes: [] },
    { id: "cl33", num: 33, phase: "6-3", category: "Logistics", task: "Guest transport confirmed", details: "Hiace Wagon rental for venue-Airbnb shuttles. Shinkansen instructions for guests.", timeline: "6-3 months", owner: "us", status: "not-started", weddingDay: "day1", notes: [] },
    { id: "cl34", num: 34, phase: "6-3", category: "Logistics", task: "Nijikai (after party) venue booked", details: "Local izakaya or karaoke room for late-night celebrations.", timeline: "6-3 months", owner: "us", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl35", num: 35, phase: "6-3", category: "Logistics", task: "Pre-wedding activities finalized", details: "Sake brewery tours, onsen visits, hiking, or other group experiences.", timeline: "6-3 months", owner: "us", status: "not-started", weddingDay: "day2", notes: [] },
    { id: "cl36", num: 36, phase: "6-3", category: "Logistics", task: "Family Meet and Greet planned", details: "Traditional yuino-style or casual dinner. Confirm format and venue.", timeline: "6-3 months", owner: "shared", status: "not-started", weddingDay: "day1", notes: [] },
    { id: "cl37", num: 37, phase: "6-3", category: "Logistics", task: "Rehearsal plan", details: "Will there be a rehearsal? Where, when, who attends?", timeline: "6-3 months", owner: "shared", status: "not-started", weddingDay: "day2", notes: [] },
    { id: "cl38", num: 38, phase: "6-3", category: "Attire", task: "Wedding dress and tux", details: "Source, purchase, and arrange fittings. Confirm transport to Japan.", timeline: "6-3 months", owner: "them", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl39", num: 39, phase: "6-3", category: "Attire", task: "Kimono dresser (kitsuke) booked", details: "Professional dresser for family members wanting to wear kimono.", timeline: "6-3 months", owner: "us", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl40", num: 40, phase: "6-3", category: "Attire", task: "Bridesmaid/groomsmen attire confirmed", details: "Confirm count, style, and sourcing plan.", timeline: "6-3 months", owner: "them", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl41", num: 41, phase: "6-3", category: "Ceremony and Reception Details", task: "Ceremony program drafted", details: "Processional order, readings, vows, cultural elements (sake ceremony, san-san-kudo, etc.).", timeline: "6-3 months", owner: "shared", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl42", num: 42, phase: "6-3", category: "Ceremony and Reception Details", task: "Speeches and MC confirmed", details: "Who speaks, in what order, who MCs (if anyone). Share timing expectations.", timeline: "6-3 months", owner: "shared", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl43", num: 43, phase: "6-3", category: "Ceremony and Reception Details", task: "Aisle decor finalized", details: "Small meadow clusters of pink flowers at chair bases. Confirm with florist.", timeline: "6-3 months", owner: "us", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl44", num: 44, phase: "3-2", category: "Vendor Confirmations", task: "Final headcount to caterer", details: "Locked guest count with dietary requirements.", timeline: "3-2 months", owner: "us", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl45", num: 45, phase: "3-2", category: "Vendor Confirmations", task: "Final floral order confirmed", details: "Specific stem counts, arrangement sizes, delivery time.", timeline: "3-2 months", owner: "us", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl46", num: 46, phase: "3-2", category: "Vendor Confirmations", task: "Rental order finalized", details: "Exact table count, chair count, lighting plan, AV equipment.", timeline: "3-2 months", owner: "us", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl47", num: 47, phase: "3-2", category: "Vendor Confirmations", task: "Sound system confirmed", details: "Portable speaker for ceremony or live musician logistics + reception AV for speeches.", timeline: "3-2 months", owner: "us", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl48", num: 48, phase: "3-2", category: "Vendor Confirmations", task: "HMUA trial or look confirmation", details: "In-person trial if possible, or confirm via photo references.", timeline: "3-2 months", owner: "shared", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl49", num: 49, phase: "3-2", category: "Timeline and Coordination", task: "Master day-of timeline drafted", details: "Setup times, vendor arrivals, HMUA start, first look, ceremony, cocktail hour, reception, speeches, cake, nijikai.", timeline: "3-2 months", owner: "us", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl50", num: 50, phase: "3-2", category: "Timeline and Coordination", task: "Photographer shot list and timeline shared", details: "Coordinate schedule, key moments, family groupings, golden hour timing.", timeline: "3-2 months", owner: "shared", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl51", num: 51, phase: "3-2", category: "Timeline and Coordination", task: "Point-of-contact list created", details: "Every vendor, every key guest, emergency numbers, hospital, taxi companies.", timeline: "3-2 months", owner: "us", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl52", num: 52, phase: "3-2", category: "Timeline and Coordination", task: "Bride Ready timeline locked", details: "Camera-ready 90 min before ceremony for first look in the forest/lakeside.", timeline: "3-2 months", owner: "us", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl53", num: 53, phase: "3-2", category: "Design Finalization", task: "Welcome gifts / favors produced", details: "If doing, source and assemble Nagano-themed welcome bags.", timeline: "3-2 months", owner: "shared", status: "not-started", weddingDay: "day1", notes: [] },
    { id: "cl54", num: 54, phase: "3-2", category: "Design Finalization", task: "Signage produced", details: "Welcome sign, seating chart, bar menu, table numbers. Confirm design and print.", timeline: "3-2 months", owner: "shared", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl55", num: 55, phase: "2-1", category: "Final Guest and Budget Management", task: "Final RSVP chase", details: "Follow up with non-responders. Lock final numbers.", timeline: "2-1 months", owner: "them", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl56", num: 56, phase: "2-1", category: "Final Guest and Budget Management", task: "Seating arrangement drafted", details: "If seated dinner, create table assignments.", timeline: "2-1 months", owner: "shared", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl57", num: 57, phase: "2-1", category: "Final Guest and Budget Management", task: "Final budget reconciliation", details: "All vendor payments scheduled, remaining balances confirmed.", timeline: "2-1 months", owner: "us", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl58", num: 58, phase: "2-1", category: "Final Guest and Budget Management", task: "Second planning fee installment", details: "Collect per payment terms.", timeline: "2-1 months", owner: "us", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl59", num: 59, phase: "2-1", category: "Pre-Event Prep", task: "Weather monitoring begins", details: "Check historical May weather for Nagano. Refine Plan B trigger criteria.", timeline: "2-1 months", owner: "us", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl60", num: 60, phase: "2-1", category: "Pre-Event Prep", task: "Final minpaku walkthrough", details: "Juri on-site if possible. Confirm layout, furniture placement, kitchen status.", timeline: "2-1 months", owner: "us", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl61", num: 61, phase: "2-1", category: "Pre-Event Prep", task: "Guest welcome packet assembly", details: "Print itinerary cards, assemble bags with treats and info.", timeline: "2-1 months", owner: "us", status: "not-started", weddingDay: "day1", notes: [] },
    { id: "cl62", num: 62, phase: "2-1", category: "Pre-Event Prep", task: "Confirm all guest travel booked", details: "Flights, Shinkansen, accommodation. Flag anyone unbooked.", timeline: "2-1 months", owner: "them", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl63", num: 63, phase: "WEEKS", category: "Final Vendor and Logistics", task: "Final vendor confirmation calls", details: "Every vendor reconfirmed with times, locations, contact numbers.", timeline: "Final weeks", owner: "us", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl64", num: 64, phase: "WEEKS", category: "Final Vendor and Logistics", task: "Day-of emergency kit prepared", details: "Sewing kit, stain remover, pain relievers, phone chargers, safety pins, tissues, etc.", timeline: "Final weeks", owner: "us", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl65", num: 65, phase: "WEEKS", category: "Final Vendor and Logistics", task: "Setup and teardown schedule finalized", details: "Who arrives when, who breaks down, cleanup responsibility for minpaku.", timeline: "Final weeks", owner: "us", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl66", num: 66, phase: "WEEKS", category: "Final Vendor and Logistics", task: "Weather call Plan A or B", details: "Final decision on ceremony location based on forecast.", timeline: "Final weeks", owner: "us", status: "not-started", weddingDay: "day3", notes: [] },
    { id: "cl67", num: 67, phase: "WEEKS", category: "Final Vendor and Logistics", task: "Final vendor payments", details: "All remaining balances paid.", timeline: "Final weeks", owner: "us", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl68", num: 68, phase: "WEEKS", category: "Final Vendor and Logistics", task: "Welcome packets distributed", details: "Delivered to accommodation before guest arrival.", timeline: "Final weeks", owner: "us", status: "not-started", weddingDay: "day1", notes: [] },
    { id: "cl69", num: 69, phase: "WEEKS", category: "Final Vendor and Logistics", task: "Rehearsal", details: "If planned, walk-through of ceremony, procession, positions.", timeline: "Final weeks", owner: "us", status: "not-started", weddingDay: "day2", notes: [] },
    { id: "cl70", num: 70, phase: "WEEKS", category: "Final Vendor and Logistics", task: "Juri on-site coordination schedule locked", details: "Where she is every hour of every day during wedding week.", timeline: "Final weeks", owner: "us", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl71", num: 71, phase: "POST", category: "Post-Wedding", task: "Teardown and property return", details: "Minpaku returned to original condition. All rentals collected.", timeline: "Post-wedding", owner: "us", status: "not-started", weddingDay: "day5", notes: [] },
    { id: "cl72", num: 72, phase: "POST", category: "Post-Wedding", task: "Farewell brunch / group departure", details: "Organize final group activity or meal.", timeline: "Post-wedding", owner: "us", status: "not-started", weddingDay: "day4", notes: [] },
    { id: "cl73", num: 73, phase: "POST", category: "Post-Wedding", task: "Thank-you notes / gifts", details: "Couple handles. Flag timeline (within 2-3 months of wedding).", timeline: "Post-wedding", owner: "them", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl74", num: 74, phase: "POST", category: "Post-Wedding", task: "Photo delivery timeline confirmed", details: "Coordinate with photographer on expected delivery.", timeline: "Post-wedding", owner: "shared", status: "not-started", weddingDay: null, notes: [] },
    { id: "cl75", num: 75, phase: "POST", category: "Post-Wedding", task: "Request marketing permissions", details: "Per agreement Section 8. Get written consent for portfolio use.", timeline: "Post-wedding", owner: "us", status: "not-started", weddingDay: null, notes: [] },
  ],
};

export default defaultData;
